version: "3.8"
services:
    nginx:
      image: nginx:1337
      build: ./requirements/nginx
      container_name: nginx
      ports:
        - 443:443
      env_file:
        - .env
      volumes:
        - wordpress_v:/var/www
      restart: always
      depends_on:
        - wordpress
      networks: 
        - moulSwa

    mariadb:
      image: mariadb:1337
      build: ./requirements/mariadb
      container_name: mariadb
      env_file:
        - .env
      volumes:
        - mariadb_v:/var/lib/mysql
      restart: always
      networks: 
        - moulSwa
        
    wordpress:
      image: wordpress:1337
      build: ./requirements/wordpress
      container_name: wordpress
      env_file:
        - .env
      volumes:
        - wordpress_v:/var/www
      restart: always
      depends_on:
        - mariadb
      networks: 
        - moulSwa

    static:
      image: static:1337
      build: ./requirements/bonus/static
      container_name: static
      env_file:
        - .env
      ports:
        - 8200:8200
      restart: always
      networks: 
        - moulSwa
    
    adminer:
      image: adminer:1337
      build: ./requirements/bonus/adminer
      container_name: adminer
      env_file:
        - .env
      ports:
        - 8080:8080
      depends_on:
        - mariadb
      restart: always
      networks:
        - moulSwa

volumes:
  wordpress_v:
    driver_opts:
      o: bind
      type: none
      device: /home/mnassi/data/wordpress_v
  mariadb_v:
    driver_opts:
      o: bind
      type: none
      device: /home/mnassi/data/mariadb_v
networks:
  moulSwa:
    driver: bridge

