FROM debian:bullseye

RUN apt-get update -y && apt-get upgrade -y && apt-get install mariadb-server -y

RUN sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf

COPY ./tools/script.sh /tmp/script.sh

RUN chmod +x /tmp/script.sh

CMD ["/tmp/script.sh"]