FROM debian:oldstable

WORKDIR /var/www

RUN apt-get update -y && apt-get upgrade -y && apt-get install wget php php-mysqli -y

EXPOSE 8080


RUN wget https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php -O /var/www/index.php

CMD ["php", "-S", "0.0.0.0:8080" , "-t", "/var/www"]