FROM debian:oldstable

RUN apt-get update -y && apt-get upgrade -y && apt-get install wget php php-mysqli -y

WORKDIR /var/www

RUN wget https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php -O /var/www/adminer.php


CMD ["php", "-S", "0.0.0.0:8080" , "-t", "/var/www"]