FROM debian:oldstable

WORKDIR /var/www

RUN apt-get update -y && apt-get upgrade -y && apt-get install php-fpm php-mysql curl -y

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
	&& chmod +x wp-cli.phar \
	&& mv wp-cli.phar /usr/local/bin/wp

RUN     sed -i "s|listen = /run/php/php7.4-fpm.sock|listen = 9000|g" /etc/php/7.4/fpm/pool.d/www.conf
RUN     mkdir -p /run/php

COPY ./tools/script.sh /tmp/script.sh

RUN chmod +x /tmp/script.sh

CMD ["./tmp/script.sh"]