FROM debian:oldstable

RUN apt-get update -y && apt-get upgrade -y && apt-get install vim nginx openssl -y

RUN mkdir -p /etc/ssl/

RUN openssl req -x509 -sha256 -days 356 -nodes -newkey rsa:2048 -subj "/CN=demo.mlopshub.com/C=US/L=San Fransisco" -keyout /etc/ssl/server.key -out /etc/ssl/server.crt

COPY ./conf/nginx.conf /etc/nginx/sites-available/default

CMD ["nginx", "-g", "daemon off;"]
